config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  root to: redirect("/live")

  namespace :api do
    resources :webhooks, only: :none do
      collection do
        get :facebook, action: :verify
        post :facebook, action: :update
      end
    end

    resource :seed_accounts, only: [:edit] do
      collection do
        get :get_account_like
        get :get_account_share
        get :get_account_comment
        post :set_account_like
        post :set_account_share
        post :set_account_comment
        post :reset_like
        post :reset_share
        post :reset_comment
      end
    end

    resource :comments, only: [] do
      collection do
        get :get_comment
      end
    end
  end

  namespace :live do
    root 'streams#index'
    resources :streams, only: [:index, :show]
  end

  namespace :management do
    root 'posts#index'
    resources :posts do
      member do
        get :channels
        get :channel, controller: :posts, action: :new_channel
        patch :channel, controller: :posts, action: :create_channel
        delete :channel, controller: :posts, action: :destroy_channel
      end
    end
    resources :channels
    resources :socials do
      collection do
        put :apply, action: :apply
      end
    end
    resources :seed_accounts do
      collection do
        patch :reset_like, action: :reset_like
        patch :reset_share, action: :reset_share
        patch :reset_comment, action: :reset_comment
      end
    end
    resources :comments
  end

  mount Crono::Web, at: '/crono'
end

app/models/seed_account.rb
class SeedAccount < ActiveRecord::Base
  enum like_status: [:like_not_seed, :like_seeding, :like_seeded]
  enum share_status: [:share_not_seed, :share_seeding, :share_seeded]
  enum comment_status: [:comment_not_seed, :comment_seeding, :comment_seeded]

  def display_like_status
    case like_status
      when :like_not_seed.to_s
        'NOT SEED'
      when :like_seeding.to_s
        'SEEDING'
      when :like_seeded.to_s
        'SEEDED'
      else
        'NOT SEED'
    end
  end

  def display_share_status
    case share_status
      when :share_not_seed.to_s
        'NOT SEED'
      when :share_seeding.to_s
        'SEEDING'
      when :share_seeded.to_s
        'SEEDED'
      else
        'NOT SEED'
    end
  end

  def display_comment_status
    case comment_status
      when :comment_not_seed.to_s
        'NOT SEED'
      when :comment_seeding.to_s
        'SEEDING'
      when :comment_seeded.to_s
        'SEEDED'
      else
        'NOT SEED'
    end
  end
end

app/controllers/api/seed_accounts_controller.rb
class Api::SeedAccountsController < Api::BaseController
  before_action :set_seed_account, only: [:set_account_like, :set_account_share, :set_account_comment]

  def get_account_like
    seed_account = SeedAccount.like_seeding.order(:email).first
    if seed_account.blank?
      seed_account = SeedAccount.like_not_seed.order(:email).first
    end
    render json: seed_account.as_json
  end

  def get_account_share
    seed_account = SeedAccount.share_seeding.order(:email).first
    if seed_account.blank?
      seed_account = SeedAccount.share_not_seed.order(:email).first
    end
    render json: seed_account.as_json
  end

  def get_account_comment
    seed_account = SeedAccount.comment_seeding.order(:email).first
    if seed_account.blank?
      offset = rand(SeedAccount.comment_not_seed.count)
      seed_account = SeedAccount.comment_not_seed.offset(offset).first
    end
    render json: seed_account.as_json
  end

  def set_account_like
    @seed_account.like_status = "like_#{set_params[:status]}"
    @seed_account.save
    render json: {
        success: true
    }
  end

  def set_account_share
    @seed_account.share_status = "share_#{set_params[:status]}"
    @seed_account.save
    render json: {
        success: true
    }
  end

  def set_account_comment
    @seed_account.comment_status = "comment_#{set_params[:status]}"
    @seed_account.save
    render json: {
        success: true
    }
  end

  def reset_like
    SeedAccount.update_all(like_status: :like_not_seed.to_s)
    render json: {
        success: true
    }
  end

  def reset_share
    SeedAccount.update_all(share_status: :share_not_seed.to_s)
    render json: {
        success: true
    }
  end

  def reset_comment
    SeedAccount.update_all(comment_status: :comment_not_seed.to_s)
    render json: {
        success: true
    }
  end

  private
  def set_seed_account
    @seed_account = SeedAccount.find(params[:id])
  end

  def set_params
    params.permit(:status)
  end
end

app/controllers/management/base_controller.rb
class Management::BaseController < ApplicationController
  before_action :authenticate_admin!
  before_action :setup
  layout 'management'

  protected
  def current_ability
    @current_ability ||= Ability.new(current_admin)
  end

  def query_params
    params.permit(:search, :sort, :page, :per)
  end

  private
  def setup
    Koala.config.api_version = ENV['FACEBOOK_API_VERSION']
  end
end

app/controllers/management/channels_controller.rb
class Management::ChannelsController < Management::BaseController
  before_action :set_channel, only: [:edit, :update, :destroy]

  def index
    @channels = ChannelQuery.new(query_params).results
  end

  def new
    authorize! :create, Channel
    @form =  Management::ChannelForm.new
  end

  def create
    authorize! :create, Channel
    @form = Management::ChannelForm.new(channel_params)
    service = Management::ChannelService.new(@form)

    if service.call
      redirect_to management_channels_path, notice: 'Channel was successfully created.'
    else
      render :new
    end
  end

  def edit
    authorize! :edit, @channel
    @form = Management::ChannelForm.new(channel_attributes)
  end

  def update
    authorize! :update, @channel
    @form = Management::ChannelForm.new(channel_params, channel_attributes)
    service = Management::ChannelService.new(@form, @channel)

    if service.call
      redirect_to management_channels_path, notice: 'Channel was successfully updated'
    else
      render :edit, alert: 'Channel was not updated. Please try again'
    end
  end

  def destroy
    authorize! :destroy, @channel
    @channel.destroy
    redirect_to management_channels_path, notice: 'Channel was successfully deleted.'
  end

  private
  def set_channel
    @channel = Channel.find(params[:id])
  end

  def channel_attributes
    @channel.slice(:name, :url, :key)
  end

  def channel_params
    params.require(:channel_form).permit(:name, :key, :url)
  end
end

app/controllers/management/comments_controller.rb
class Management::CommentsController < Management::BaseController
  before_action :set_comment, only: [:edit, :update, :destroy]
  before_action :set_presenter, only: [:new, :create, :edit, :update]

  def index
    @comments = CommentQuery.new(query_params).results
  end

  def new
    authorize! :create, Comment
    @form =  Management::CommentForm.new
  end

  def create
    authorize! :create, Comment
    @form = Management::CommentForm.new(comment_params)
    service = Management::CommentService.new(@form)

    if service.call
      redirect_to management_comments_path, notice: 'Comment was successfully created.'
    else
      render :new
    end
  end

  def edit
    authorize! :edit, @comment
    @form = Management::CommentForm.new(comment_attributes)
  end

  def update
    authorize! :update, @comment
    @form = Management::CommentForm.new(comment_params, comment_attributes)
    service = Management::CommentService.new(@form, @comment)

    if service.call
      redirect_to management_comments_path, notice: 'Comment was successfully updated'
    else
      render :edit, alert: 'Comment was not updated. Please try again'
    end
  end

  def destroy
    authorize! :destroy, @comment
    @comment.destroy
    redirect_to management_comments_path, notice: 'Comment was successfully deleted.'
  end

  private
  def set_comment
    @comment = Comment.find(params[:id])
  end

  def set_presenter
    @presenter = CommentPresenter.new
  end

  def comment_attributes
    @comment.slice(:content, :category)
  end

  def comment_params
    params.require(:comment_form).permit(:content, :category)
  end
end

app/controllers/management/posts_controller.rb
class Management::PostsController < Management::BaseController
  before_action :set_post, only: [:edit, :update, :destroy, :channels, :new_channel, :create_channel, :destroy_channel]
  before_action :set_presenter, only: [:new_channel, :create_channel]

  def index
    @posts = PostQuery.new(query_params).results
  end

  def new
    authorize! :create, Post
    @form =  Management::PostForm.new
  end

  def create
    authorize! :create, Post
    @form = Management::PostForm.new(post_params)
    service = Management::PostService.new(@form)

    if service.call
      redirect_to management_posts_path, notice: 'Media Owner was successfully created.'
    else
      render :new
    end
  end

  def edit
    authorize! :edit, @post
    @form = Management::PostForm.new(post_attributes)
  end

  def update
    authorize! :update, @post
    @form = Management::PostForm.new(post_params, post_attributes)
    service = Management::PostService.new(@form, @post)

    if service.call
      redirect_to management_posts_path, notice: 'Post was successfully updated'
    else
      render :edit, alert: 'Post was not updated. Please try again'
    end
  end

  def destroy
    authorize! :destroy, @post
    @post.destroy
    redirect_to management_posts_path, notice: 'Post was successfully deleted.'
  end

  def channels
  end

  def new_channel
    authorize! :create, PostChannel
    @form = Management::PostChannelForm.new
  end

  def create_channel
    authorize! :create, PostChannel
    @form = Management::PostChannelForm.new(post_channel_params)
    service = Management::PostChannelService.new(@form, @post)

    if service.call
      redirect_to channels_management_post_path(@post), notice: 'Linked a new channel successful.'
    else
      render :new_channel
    end
  end

  def destroy_channel
    authorize! :destroy_channel, Channel
    @post.channels.delete(Channel.find(params[:channel_id]))
    redirect_to channels_management_post_path(@post), notice: 'Linked Channel was successfully deleted.'
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end

  def set_presenter
    @presenter = PostPresenter.new(@post)
  end

  def post_attributes
    @post.slice(:url, :title, :description)
  end

  def post_params
    params.require(:post_form).permit(:url, :title, :description)
  end

  def post_channel_params
    params.require(:post_channel_form).permit(:channel_id)
  end
end

app/controllers/management/seed_accounts_controller.rb
class Management::SeedAccountsController < Management::BaseController
  before_action :set_seed_account, only: [:edit, :update, :destroy]
  before_action :set_presenter, only: [:new, :create, :edit, :update]

  def index
    @seed_accounts = SeedAccountQuery.new(query_params).results
  end

  def new
    authorize! :create, SeedAccount
    @form =  Management::SeedAccountForm.new
  end

  def create
    authorize! :create, SeedAccount
    @form = Management::SeedAccountForm.new(seed_account_params)
    service = Management::SeedAccountService.new(@form)

    if service.call
      redirect_to management_seed_accounts_path, notice: 'Seed Account was successfully created.'
    else
      render :new
    end
  end

  def edit
    authorize! :edit, @seed_account
    @form = Management::SeedAccountForm.new(seed_account_attributes)
  end

  def update
    authorize! :update, @seed_account
    @form = Management::SeedAccountForm.new(seed_account_params, seed_account_attributes)
    service = Management::SeedAccountService.new(@form, @seed_account)

    if service.call
      redirect_to management_seed_accounts_path, notice: 'Seed Account was successfully updated'
    else
      render :edit, alert: 'Seed Account was not updated. Please try again'
    end
  end

  def destroy
    authorize! :destroy, @seed_account
    @seed_account.destroy
    redirect_to management_seed_accounts_path, notice: 'Seed Account was successfully deleted.'
  end

  def reset_like
    SeedAccount.update_all(like_status: :like_not_seed.to_s)
    redirect_to management_seed_accounts_path, notice: 'All Seed Account was successfully reset.'
  end

  def reset_share
    SeedAccount.update_all(share_status: :share_not_seed.to_s)
    redirect_to management_seed_accounts_path, notice: 'All Seed Account was successfully reset.'
  end

  def reset_comment
    SeedAccount.update_all(comment_status: :comment_not_seed.to_s)
    redirect_to management_seed_accounts_path, notice: 'All Seed Account was successfully reset.'
  end

  private
  def set_seed_account
    @seed_account = SeedAccount.find(params[:id])
  end

  def set_presenter
    @presenter = SeedAccountPresenter.new
  end

  def seed_account_attributes
    @seed_account.slice(:email, :password, :like_status, :share_status, :comment_status)
  end

  def seed_account_params
    params.require(:seed_account_form).permit(:email, :password, :like_status, :share_status, :comment_status)
  end
end

app/controllers/management/socials_controller.rb
class Management::SocialsController < Management::BaseController
  def index
    fb_token = Config.where(key: ENV['FACEBOOK_TOKEN_KEY']).first
    unless fb_token.blank?
      begin
        response = RestClient.get "#{ENV['FACEBOOK_GRAPH_URL']}/debug_token", {params: {input_token: fb_token.value, access_token: fb_token.value}}
        if response && response.code == 200
          token_info = JSON.parse(response.body)
          @status = token_info['data']['is_valid'] ? 'Connected' : '...'
          @access_token = fb_token.value
          @expires_at = token_info['data']['expires_at'] == 0 ? 'Never' : DateTime.strptime(token_info['data']['expires_at'].to_s, '%s').strftime('%a, %d %b %Y %H:%M %Z')
          @user_id = token_info['data']['user_id']
        end
      rescue Exception => e
        Rails.logger.info "#{e.message}"
        puts caller
      end
    end
  end

  def apply
    fb_token_conf = Config.where(key: ENV['FACEBOOK_TOKEN_KEY']).first
    if fb_token_conf.blank?
      fb_token_conf = Config.new
      fb_token_conf.key = ENV['FACEBOOK_TOKEN_KEY']
    end

    if apply_params[:access_token].blank?
      @status_code = 0
    else
      fb_token = apply_params[:access_token]
      graph = Koala::Facebook::API.new(fb_token)
      oauth_params = {
          grant_type: 'fb_exchange_token',
          client_id: ENV['FACEBOOK_APP_ID'],
          client_secret: ENV['FACEBOOK_APP_SECRET'],
          fb_exchange_token: fb_token
      }

      token_info = graph.get_connections('oauth', 'access_token', oauth_params)
      if token_info['access_token'].blank?
        raise 'Long-lived token not found'
      else
        fb_token_conf.value = token_info['access_token']
        fb_token_conf.save
        data = graph.get_connections('me', 'accounts')
        if data.blank?
          @status_code = 1
        else
          page = data.detect { |page|
            page['id'] == ENV['FACEBOOK_PAGE_ID']
          }

          if page.blank?
            @status_code = 2
          else
            page_token = page['access_token']
            puts page_token
            if page_token.blank?
              @status_code = 3
            else
              graph = Koala::Facebook::API.new(page_token)
              subcribe_result = graph.put_connections(ENV['FACEBOOK_PAGE_ID'], 'subscribed_apps')
              if subcribe_result.blank?
                @status_code = 4
              elsif subcribe_result['success']
                @status_code = 6
              else
                @status_code = 5
              end
            end
          end
        end
      end
    end

    respond_to do |format|
      format.js do
        render layout: false
      end
    end
  end

  private
  def apply_params
    params.permit(:access_token)
  end
end

app/views/management/seed_accounts/edit.html.slim
= render partial: 'management/shared/header', locals: {titles: ['Seed Accounts', 'Edit Seed Account'], paths: [{name: 'Seed Accounts', url: management_seed_accounts_path}]}
section.content.seed-accounts
  .row
    .col-xs-12
      .box.box-success
        .box-header.with-border
          h3.box-title Edit Seed Account
        = simple_form_for @form, as: :seed_account_form, url: management_seed_account_path(@seed_account), method: :patch do |f|
          .box-body
            = f.input :email, label: 'Email'
            = f.input :password, as: :string, label: 'Password'
            = f.input :like_status, label: 'Like Status', collection: @presenter.like_statuses, include_blank: false
            = f.input :share_status, label: 'Share Status', collection: @presenter.share_statuses, include_blank: false
            = f.input :comment_status, label: 'Comment Status', collection: @presenter.comment_statuses, include_blank: false
          .box-footer
            = link_to 'Back', management_seed_accounts_path, class: 'btn btn-default'
            = f.submit 'Save', class: 'btn btn-success'

app/views/management/seed_accounts/index.html.slim
= render partial: 'management/shared/header', locals: {titles: ['Seed Accounts']}
section.content.seed-accounts
  .row
    .col-xs-12
      = link_to 'Add New Seed Account', new_management_seed_account_path, class: 'btn btn-success'
      = link_to 'Reset All Like', reset_like_management_seed_accounts_path, method: :patch, class: 'btn btn-primary', style: 'margin-left: 15px;'
      = link_to 'Reset All Share', reset_share_management_seed_accounts_path, method: :patch, class: 'btn btn-primary', style: 'margin-left: 15px;'
      = link_to 'Reset All Comment', reset_comment_management_seed_accounts_path, method: :patch, class: 'btn btn-primary', style: 'margin-left: 15px;'
      .box
        .box-header
          h3.box-title = "All Accounts (#{@seed_accounts.count})"
          .box-tools
            .input-group.input-group-sm style=("width: 150px;")
              input.form-control.pull-right name="table_search" placeholder="Search" type="text" /
              .input-group-btn
                button.btn.btn-default type="submit"
                  i.fa.fa-search
        .box-body.table-responsive.no-padding
          table.table.table-hover
            thead
              tr
                th Email
                th Password
                th Like Status
                th Share Status
                th Comment Status
                th Actions
            tbody
              - @seed_accounts.each do |acc|
                tr.seed-account
                  td = acc.email
                  td = acc.password
                  td = acc.display_like_status
                  td = acc.display_share_status
                  td = acc.display_comment_status
                  td.actions
                    - if can?(:update, acc)
                      = link_to edit_management_seed_account_path(acc) do
                        i.fa.fa-edit
                    - if can?(:destroy, acc)
                      = link_to management_seed_account_path(acc), data: {confirm: 'Are you sure?'}, method: :delete do
                        i.fa.fa-window-close
  .row
    .col-xs-12.text-center
      = paginate @seed_accounts

app/views/management/seed_accounts/new.html.slim
= render partial: 'management/shared/header', locals: {titles: ['Seed Accounts', 'New Seed Account'], paths: [{name: 'Seed Accounts', url: management_seed_accounts_path}]}
section.content.seed_accounts
  .row
    .col-xs-12
      .box.box-success
        .box-header.with-border
          h3.box-title New Seed Account
        = simple_form_for @form, as: :seed_account_form, url: management_seed_accounts_path, method: :post do |f|
          .box-body
            = f.input :email, label: 'Email'
            = f.input :password, as: :string, label: 'Password'
            = f.input :like_status, label: 'Like Status', collection: @presenter.like_statuses, include_blank: false
            = f.input :share_status, label: 'Share Status', collection: @presenter.share_statuses, include_blank: false
            = f.input :comment_status, label: 'Comment Status', collection: @presenter.comment_statuses, include_blank: false
          .box-footer
            = link_to 'Back', management_seed_accounts_path, class: 'btn btn-default'
            = f.submit 'Save', class: 'btn btn-success'